apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: sumapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sumapp
    spec:
      containers:
      - name: sumapp
        image: mycluster.icp:8500/samirman/sumapp
        ports:
        - containerPort: 9080
